// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV1Ltg8HhS8fbqoCZ-Z-Uz7G7kWKiIlk4',
    appId: '1:545546465233:web:d68f083733e441f77a7af0',
    messagingSenderId: '545546465233',
    projectId: 'lukitask-5af6f',
    authDomain: 'lukitask-5af6f.firebaseapp.com',
    storageBucket: 'lukitask-5af6f.firebasestorage.app',
    measurementId: 'G-9YDGY4BXG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQWrO4crRLS1Vohb7iKdNOOR6M3YkSmA',
    appId: '1:545546465233:android:4d1d187a82a3f2597a7af0',
    messagingSenderId: '545546465233',
    projectId: 'lukitask-5af6f',
    storageBucket: 'lukitask-5af6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPgazqVQisPGpg4dKQ7XMGz5xodTtzWP8',
    appId: '1:545546465233:ios:839cb266a93da5527a7af0',
    messagingSenderId: '545546465233',
    projectId: 'lukitask-5af6f',
    storageBucket: 'lukitask-5af6f.firebasestorage.app',
    iosBundleId: 'com.example.lukitask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPgazqVQisPGpg4dKQ7XMGz5xodTtzWP8',
    appId: '1:545546465233:ios:839cb266a93da5527a7af0',
    messagingSenderId: '545546465233',
    projectId: 'lukitask-5af6f',
    storageBucket: 'lukitask-5af6f.firebasestorage.app',
    iosBundleId: 'com.example.lukitask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV1Ltg8HhS8fbqoCZ-Z-Uz7G7kWKiIlk4',
    appId: '1:545546465233:web:03aaf94026b9e23e7a7af0',
    messagingSenderId: '545546465233',
    projectId: 'lukitask-5af6f',
    authDomain: 'lukitask-5af6f.firebaseapp.com',
    storageBucket: 'lukitask-5af6f.firebasestorage.app',
    measurementId: 'G-T8BQBB2DGV',
  );

}